"""add rfp_projects table

Revision ID: 0568c86c0a8e
Revises: afb508661cea
Create Date: 2026-09-23 17:25:17.012274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0568c86c0a8e'
down_revision: Union[str, Sequence[str], None] = 'afb508661cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfp_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('buyer', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'questions_confirmed', 'drafting', 'drafted', name='project_status'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('source_file_key', sa.String(length=512), nullable=False),
    sa.Column('source_file_ext', sa.String(length=10), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfp_projects_org_id'), 'rfp_projects', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfp_projects_org_id'), table_name='rfp_projects')
    op.drop_table('rfp_projects')
    # ### end Alembic commands ###
